### ISSUE TITLE
Escape naked pointers

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#1]
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/Test.cpp#L12

You can use non-pointer object or smart pointer. And create objects in main, remove globals

**Comment by ChristoMI** [comment]
What if I am using them further in the "clearMemory()" method. Will it be ok to clear them inside main then?

**Comment by ChristoMI** [comment]
Corrected
