### ISSUE TITLE
New method

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#10]
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/DiffusionMap.cpp#L53

Consider introdusing a new method for very similar code

**Comment by ChristoMI** [comment]
Revised
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/DiffusionMap.cpp#L55
