### ISSUE TITLE
Can be nullptr?

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#11]
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/DiffusionMap.cpp#L51

can map[xPos][yPos] be nullptr?

**Comment by ChristoMI** [comment]
No it cannot be. This operation is only performed for initialized cities (according to countries' positions).
