### ISSUE TITLE
Uninitialized value

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#13]
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/City.h#L20

completeState is not initialized in ctor

**Comment by ChristoMI** [comment]
It is initialized in parameterized ctor
`state = DEFAULT_STATE - (capacity - DEFAULT_STATE);`

**Comment by ChristoMI** [comment]
[https://github.com/ChristoMI/SDT_Practice2/blob/master/Test/City.cpp#L19](url)

**Comment by IanaKhitsko** [comment]
ok, sure
