### ISSUE TITLE
Uninitialized values

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#16]
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/Country.h#L29

Again, pointer is pointing on garbage in ctor, completionSteps is uninitialized, how does this work at all?

**Comment by ChristoMI** [comment]
Actually, cities is an unused field. Forgot to remove it.
Initialization of 'name' and 'completionSteps' fields corrected.
