### ISSUE TITLE
Typedef void and int

### ISSUE THREAD

**Issue by AndreyKrysiuk** [ChristoMI/SDT_Practice2#18]
Is it really need to typedef void and int? If you want to present int as state of something, it's better to use enum. 

https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/City.h#L10-L12

**Comment by ChristoMI** [comment]
Just a flexible approach in case I need to change the return type or the type I operate.
