### ISSUE TITLE
Simplify function

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#21]
https://github.com/ChristoMI/SDT_Practice2/blob/216dc4fa79f1cefffe9e29385d8ae2f76700ca6f/Test/Initializer.cpp#L18-L28

bool Initializer::checkIntersection(Country& c1, Country& c2) {
	return ((c1.getyL() <= c2.getyL() && c1.getyR() >= c2.getyR()) ||
		    (c1.getyL() <= c2.getyR() && c1.getyR() >= c2.getyR())) &&
		    ((c1.getxR() <= c2.getxR() && c1.getxL() >= c2.getxR()) ||
			(c1.getxR() <= c2.getxL() && c1.getxL() >= c2.getxL())) ;
}

**Comment by ChristoMI** [comment]
Corrected
