### ISSUE TITLE
Consts

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#3]
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/Initializer.h#L36

const std::vector.. ?

**Comment by ChristoMI** [comment]
Adding const here will not let me change the inner structure of these vectors.

**Comment by ChristoMI** [comment]
Fixed where possible.
