### ISSUE TITLE
Please write code on c++, not c ))

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#7]
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/DiffusionMap.h#L21

std::vector<std::vector<City*>> map; 
 it will clear itself when needed. OR you can use smart pointer for the City
std::vector<std::vector<std::unique_ptr<City>>> map;

**Comment by ChristoMI** [comment]
Corrected
