### ISSUE TITLE
Uninitialized class members

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#8]
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/DiffusionMap.h#L21-L26

None of the is initialized in ctor

**Comment by ChristoMI** [comment]
They are initialized in "initStructure" method that is called every time the program is run. Should I still initialize them in constructor with some default values?

**Comment by ChristoMI** [comment]
[https://github.com/ChristoMI/SDT_Practice2/blob/master/Test/DiffusionMap.cpp#L62](url)

**Comment by IanaKhitsko** [comment]
initStructure can be not called, it is public and class user can decide.

**Comment by ChristoMI** [comment]
Revised
