### ISSUE TITLE
Const ref parameter

### ISSUE THREAD

**Issue by IanaKhitsko** [ChristoMI/SDT_Practice2#9]
https://github.com/ChristoMI/SDT_Practice2/blob/f100821a4b67589bcbef54dc89d861cefbbbde0f/Test/DiffusionMap.cpp#L16

std::pair<Coordinates, Coordinates> DiffusionMap::composeCoordinates(const & countries)

**Comment by IanaKhitsko** [comment]
check each method, where you pass some structure, it shall not be copied. THis is a question of performance, be careful with it.

**Comment by ChristoMI** [comment]
Corrected
